version: '3'

services:
  api:
    build: ./code
    container_name: api
    env_file:
      - .env
    volumes:
      - api-django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  api-django:
  db:
    driver: local
