version: '3'

services:
  api:
    build: ./code
    # command: python manage.py runserver 0.0.0.0:8000
    container_name: api
    environment:
      - COMMAND=gunicorn
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
