# Generated by Django 4.1.2 on 2022-10-12 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('code', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paying',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('document', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UF',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('initials', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('execution_date', models.DateField()),
                ('execution_time', models.TimeField()),
                ('election_year', models.PositiveIntegerField()),
                ('contracts', models.ManyToManyField(to='research.contract')),
                (
                    'office',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='research.office',
                    ),
                ),
                (
                    'uf',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='research.uf'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='paying',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='research.paying'
            ),
        ),
    ]
